[project]
name = "bitstack"
description = "A Stacks project"
authors = ["Bitstack Creator"]
telemetry = false
requirements = []
[project.cache_location]
path = ".requirements"
[contracts.core]
path = "contracts/core.clar"
